FROM node:20-alpine AS builder
WORKDIR /app
RUN npm install -g npm@10.9.2
COPY maintenance-frontend/package*.json ./
RUN npm ci
COPY maintenance-frontend/ .
RUN npm run build -- --configuration production

FROM nginx:alpine
RUN rm /etc/nginx/conf.d/default.conf
COPY devops/nginx-cloudrun.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist/maintenance-frontend/browser /usr/share/nginx/html
EXPOSE 80