FROM node:20-alpine AS builder
WORKDIR /app
COPY maintenance-frontend/package*.json ./
RUN npm ci --silent
COPY maintenance-frontend/ .
RUN npm run build -- --configuration production

FROM nginx:alpine
RUN rm /etc/nginx/conf.d/default.conf
COPY devops/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist/maintenance-frontend/browser /usr/share/nginx/html
EXPOSE 80
