server {
    listen 8080;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass https://maintenance-backend-107717003850.europe-west1.run.app/api/;
        proxy_set_header Host maintenance-backend-107717003850.europe-west1.run.app;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_ssl_server_name on;
    }
}