spring.application.name=maintenance-app
spring.datasource.url=jdbc:mysql://localhost:3306/usta?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
# JWT (genere une cle base64 de 256 bits)
app.jwt.secret=dGhpcyBpcyBhIHZlcnkgc2VjdXJlIHNlY3JldCBrZXkgZm9yIG1haW50ZW5hbmNlcHJv
app.jwt.expiration-ms=86400000